version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_webserver.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_app.sh
      timeout: 300
      runas: root
